### ISSUE TITLE
Cannot set --experimental_allow_proto3_optional options

### ISSUE THREAD

**Issue by xprezesx** [namely/docker-protoc#234] opened 2021-03-18 15:31 UTC
There is new option in protobuf 3 `optional`.
I can't find possibility to set this flag on `protoc` function

`docker run -v `pwd`:/defs namely/protoc-all -l php -o library/ -i --experimental_allow_proto3_optional -d ./                  1 ↵ jacekbednarek@Jacek-Shoplo-Macbook-2019
--experimental_allow_proto3_optional: warning: directory does not exist.
catalog/product/domain/product.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.`

**Comment by ido-namely** [comment] 2021-03-30 18:52
Hi @xprezesx,
please note that the docker image entrypoint does not expose protoc command line directly.
as a workaround I suppose you can override the entrypoint to `protoc` and invoke it however way you want.
Otherwise this option will need to be added as a flag to the current entrypoint script.

**Comment by wespen** [comment] 2021-03-31 07:46
Ok, took a deeper look and the problem is that a lot of generators still don't support the optional flag.

I re-test when generators include it.

**Comment by wespen** [comment] 2021-04-29 21:18
Once all packages support it Ill do MR.
(Opened up new issue in all affected repos)

Wating for proto3 optional support in packages:
protoc-gen-validate (https://github.com/envoyproxy/protoc-gen-validate/issues/431)
protoc-gen-micro (https://github.com/micro/micro/issues/1766)
protoc-gen-rbi (https://github.com/coinbase/protoc-gen-rbi/issues/24)
protoc-gen-gogofast (https://github.com/gogo/protobuf/issues/713)

**Comment by esparzak** [comment] 2022-08-03 10:26
Hi @ido-namely, are you still looking at implementing this?

**Comment by ido-namely** [comment] 2022-08-03 12:31
Hey @esparzak, 
I've looked into this further, It seems like the flag is already enabled by default since [protobuf v3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) and by now this project uses [protobuf v3.19.4](https://github.com/protocolbuffers/protobuf/tree/22d0e265de7d2b3d2e9a00d071313502e7d4cccf).

Are you sure the `optional` option is not enabled for you?
Also, we are using `optional` in one of our [tests](https://github.com/namely/docker-protoc/blob/7b29cfbd3e4d97f2d82a78c68d7c55bb26838224/all/test/all_test.go#L428).

**Comment by ido-namely** [comment] 2022-08-09 12:40
Hey @xprezesx ,
Would you agree this issue was resolved?

**Comment by ido-namely** [comment] 2022-08-22 18:03
Hi, unless anyone objects, I will consider this issue resolved and close this at the end of this week.
Thanks.

**Comment by ido-namely** [comment] 2022-08-26 19:36
As mentioned in previous comments, the flag in question seems to already enabled by default on the version of `protoc` that is used in this repo, so I'm closing this issue.

Feel free to reopen or further discuss in case you disagree.
Thanks!

**Closed by ido-namely** 2022-08-26 19:36 UTC
