### ISSUE TITLE
No service type definitions generated when using --with-typescript

### ISSUE THREAD

**Issue by bartdeslagmulder** [namely/docker-protoc#138] opened 2019-07-31 11:34 UTC
Thank you for adding the `--with-typescript` flag in PR #125. 

When using --with-typescript it seems no service type definitions are generated.

In the ts-protoc-gen docs it's mentioned to add `service=true` before the OUT_DIR, like so:
```
--ts_out="service=true:${OUT_DIR}"
```

See https://github.com/improbable-eng/ts-protoc-gen#generating-grpc-service-stubs-for-use-with-grpc-web for more info.

@esilkensen as you worked on this recently do you care to extend your current implementation with this `service=true` option?

Thanks in advance!

**Comment by esilkensen** [comment] 2019-07-31 16:03
Sure, yeah I will take a look!

**Comment by esilkensen** [comment] 2019-07-31 17:17
I wonder if it's worth making this configurable somehow?

The ts-protoc-gen README notes that 
>Both js and d.ts service files will be generated regardless of whether there are service definitions in the proto files.

So it generates empty _service.js and _service.d.ts files for each .proto file that doesn't have a service definition... (which makes me think, is there a reason those files are generated, or could ts-protoc-gen itself be updated to suppress those...)

**Comment by bartdeslagmulder** [comment] 2019-07-31 18:50
I've used another lib in the past (https://github.com/agreatfool/grpc_tools_node_protoc_ts) and that one does only generate d.ts service files if there are service definitions found.

Not sure about ts-protoc-gen.

**Comment by esilkensen** [comment] 2019-08-01 06:52
Oh, interesting -- and refreshing my memory -- so I think ts-protoc-gen with `service=true` generates JS and corresponding TypeScript declarations for [grpc-web](https://github.com/improbable-eng/grpc-web) service implementations, but not for the normal service definition generated by protoc.

I wonder if ideally ts-protoc-gen could be updated to generate TypeScript declarations for protoc-generated service implementations regardless of whether `service=true`...

**Comment by esilkensen** [comment] 2019-08-04 02:46
Oh, thanks - I think I understand more now. So it is the grpc_node_plugin that generates the gRPC JS, which is separate from the normal JS output.

It looks like https://github.com/agreatfool/grpc_tools_node_protoc_ts was forked as https://github.com/niklaus0823/protoc-gen-grpc-ts - maybe that could be leveraged to generate TypeScript declarations for gRPC services in this project instead of / in addition to ts-protoc-gen...?

**Comment by esilkensen** [comment] 2019-08-04 04:02
I think we could switch to protoc-gen-grpc-ts - but there may be one issue that would be good to resolve first:

That project generates `enum` definitions in .d.ts files, which is the only difference as far as I can tell between what it generates and ts-protoc-gen (except for it also generating the gRPC service implementation types).

But `enum` definitions are special in TypeScript and have their own implementation and shouldn't go in a .d.ts file (https://lukasbehal.com/2017-05-22-enums-in-declaration-files/)

I think I'll look into opening a PR / Issue for discussion with protoc-gen-grpc-ts and then circle back here!

**Comment by esilkensen** [comment] 2019-08-04 04:03
https://github.com/esilkensen/docker-protoc/tree/feature/node-grpc-ts-support - branch that would swap out the plugins, and potentially all it would need is a version bump if this `enum` issue is indeed a problem that could be resolved with a PR in that other repo.

**Comment by esilkensen** [comment] 2019-08-04 05:20
Actually, looking through ts-protoc-gen's history it seems like there have been attempts to add grpc-node typings to that project which just haven't made it all the way in yet -- e.g. https://github.com/improbable-eng/ts-protoc-gen/pull/75 -- maybe the best solution is to try and pickup that work since that project is more popular and better supported with test cases, etc.

**Comment by esilkensen** [comment] 2019-08-30 07:04
`ts-protoc-gen@next` now has support for generating types for both grpc-web and grpc-node services via the `service=grpc-web` (previously `service=true`) and `service=grpc-node` options.

I'm hoping that makes it into `ts-protoc-gen@latest` soon, and figured then I would open a PR here that bumps the version and adds the `service=grpc-node` option.

**Comment by bartdeslagmulder** [comment] 2019-08-30 14:55
Great! 👍

**Comment by esilkensen** [comment] 2019-09-09 22:29
@mhamrah, Thanks for merging #141! I think this issue can be closed. I confirmed that with the latest docker image, the new .d.ts files for gRPC services are generated.

@bartdeslagmulder, let me know if you get a chance to try it out and run into any issues.

**Closed** 2019-09-10 13:20 UTC
